### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by koppor** [GedMarc/JDK_Jlink_Bug#6]
When trying to build, I get following output:

```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.bugs.jlink.reproduce:jdk-jlink-parent:0.0.0_0-SNAPSHOT (c:\git-repositories\jdk\JDK_Jlink_Bug\pom.xml) has 2 errors
[ERROR]     Non-resolvable import POM: Could not find artifact com.guicedee:guicedee-bom:pom:0.0.0_0-SNAPSHOT @ line 54, column 25 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact com.guicedee:guicedee-projects:pom:0.0.0_0-SNAPSHOT @ line 61, column 25 -> [Help 2]
[ERROR]
```

Context: I am trying to create a test case for a possible fix at https://git.openjdk.org/jdk/pull/10704.

**Comment by GedMarc** [comment]
Oh I see -  this is very easy to reproduce though, let me check if its as simple as bumping the version

**Comment by GedMarc** [comment]
Sorry about the entire internet download - but it does only occur when the generated module-info method is greater than 64kb, so pops up quite a lot in monoliths - 

It is still present in JDK 18, and has been from JDK 9 ;) 
Thanks man
